on:
  push:
    branches:
      - main

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 10
          submodules: true

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/essence/

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.9
        with:
          source: src/source.scss
          destination: /tmp/essence/source.css

      - name: Checkout destination Git branch
        uses: actions/checkout@v2
        with:
          ref: build
          fetch-depth: 1

      - name: Move compiled CSS to path within build branch
        run: mv /tmp/essence/source.css src/

      - name: Add and Commit changes to build branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add .
          git commit -m 'Update compiled CSS files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build
